title: ~mtmiller
description: >
  Debian development information, custom packages, and status of Debian
  Developer mtmiller.
author: Mike Miller
email: mtmiller@debian.org
baseurl: "/~mtmiller"
url: "https://people.debian.org"
permalink: pretty
exclude: ["AUTHORS", "LICENSE", "README.md"]
